# Language maintainers for Keycloak translations
# This file maps language codes to their responsible maintainers. It is used to notify them once a translation changes.
# Format: language_code: [list of GitHub usernames]

languages:
  de:
    name: German
    maintainers:
      - ahus1
